app-config:
  #尝试重连间隔时间（单位:毫秒）
  interval: 1000
server:
    # WebServer bind port
    port: 9010


spring:
  jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.SQLiteDialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
  datasource:
      initialization-mode: never
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:springboot.db
      username:
      password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db


spring.mvc.cors:
    mappings:
       "/**":
           #Comma-separated list of origins to allow. '*' allows all origins. When not set,CORS support is disabled.
           allowed-origins: "*"
           #Comma-separated list of methods to allow. '*' allows all methods.
           allowed-methods: "*"
           #Comma-separated list of headers to allow in a request. '*' allows all headers.
           allowed-headers: "*"
           #How long, in seconds, the response from a pre-flight request can be cached by clients.
           max-age: "1800"
           #Set whether credentials are supported. When not set, credentials are not supported.
           allow-credentials: "true"