app-config:
  #尝试重连间隔时间（单位:毫秒）
  interval: 1000
server:
    # WebServer bind port
    port: 9010


spring:
#  jpa:
#      generate-ddl: false
#      hibernate:
#        ddl-auto: none
#      database-platform: org.hibernate.dialect.SQLiteDialect
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true
#          use_sql_comments: true

  datasource:
      initialization-mode: never
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:springboot.db
      username:
      password:

  boot:
    admin:
      context-path: /admin
      monitor:
        #被监控的应用信息的更新频率，单位毫秒
        period: 1000ms
        #被监控的应用信息的过期时间，单位毫秒
        status-lifetime: 1000ms
      client:
        url: http://localhost:${server.port}/admin


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: log/all.log

mybatis-plus:
  mapper-locations: classpath:com/rtucloud/cs/proxy/dao/mapper/*.xml
  config-location: classpath:mybatis-config.xml